language: c
compiler:

branches:
  only:
    - worker
    - buildnext

env:
  - APPNAME=Ruby

script:
  - cp -ra src dist
  - curl -fo dist/RUBY_VERSION.txt https://lv.binarybabel.org/catalog-api/ruby/latest.txt?p=version
  - echo "${APPNAME} latest version:" && cat dist/RUBY_VERSION.txt

after_success:
  - cd dist
  # PIN RUBY VERSION
  - export VERSION=$(cat RUBY_VERSION.txt)
  - sed -i'' "s/%VERSION%/${VERSION}/g" .travis.yml
  # CREATE GIT BUILDNEXT BRANCH FOR TRAVIS PICKUP
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git init
  - git add .
  - git commit -am "Generated Automation Base"
  - git push --quiet --force https://$GITHUBKEY@github.com/binarybabel/ruby-exception-hierarchy master:buildnext > /dev/null 2>&1

notifications:
  email: false
