language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3

branches:
  only:
    - worker
    - buildnext

env:
  - APPNAME=Ruby

after_success:
  - export VERSION=$(ruby -e 'puts "#{RUBY_VERSION}"')
  # CREATE GIT LATEST BRANCH AND TAG
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git add .
  - git commit -am "${APPNAME} ${VERSION}"
  - git tag v${VERSION} -am "${APPNAME} ${VERSION}"
  - git push --tags --quiet --force https://$GITHUBKEY@github.com/binarybabel/ruby-exception-hierarchy ${BUILD_LABEL} > /dev/null 2>&1
  #- git push https://$GITHUBKEY@github.com/binarybabel/ruby-exception-hierarchy :buildnext > /dev/null 2>&1

notifications:
  email: false
