language: ruby
rvm: %VERSION%

branches:
  only:
    - worker
    - buildnext

env:
  - APPNAME=Ruby

after_success:
  - export VERSION=$(ruby -e 'puts "#{RUBY_VERSION}"')
  # CREATE GIT LATEST BRANCH AND TAG
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - rm -rf .git
  - git init
  - git add README.md REPORT.txt
  - git commit -m "${APPNAME} ${VERSION}"
  - git tag v${VERSION} -am "${APPNAME} ${VERSION}"
  - git push --tags --quiet --force https://$GITHUBKEY@github.com/binarybabel/ruby-exception-hierarchy master:latest > /dev/null 2>&1
  - git push --quiet --force https://$GITHUBKEY@github.com/binarybabel/ruby-exception-hierarchy :buildnext > /dev/null 2>&1

notifications:
  email: false
